openapi: 3.0.0
info:
  title: Football API
  version: 1.0.0
paths:
  /matches:
    get:
      summary: Return the list of all matches
      responses:
        '200':
          description: List of matchs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Match'
  /teams:
    get:
      summary: Return the list of all teams
      responses:
        '200':
          description: List of teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
  /players:
    get:
      summary: Return the list of all players
      responses:
        '200':
          description: List of players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
components:
  schemas:
    Match:
      type: object
      properties:
        match_id:
          type: integer
          description: Unique match identifier
        home_team:
          $ref: '#/components/schemas/Team'
        away_team:
          $ref: '#/components/schemas/Team'
        date:
          type: string
          format: date
          description: Date of the match
        time:
          type: string
          format: time
          description: Hour of the match
        score:
          type: string
          description: score of the match
        scorers:
          type: array
          items:
            $ref: '#/components/schemas/Scorer'
    Team:
      type: object
      properties:
        team_id:
          type: integer
          description: Unique team identifier
        name:
          type: string
          description: Name of the team
        players:
          type: array
          items:
            $ref: '#/components/schemas/Player'
        sponsors:
          type: array
          items:
            $ref: '#/components/schemas/Sponsor'
    Player:
      type: object
      properties:
        player_id:
          type: integer
          description: Unique player identifier
        name:
          type: string
          description: Name of the player
    Scorer:
      type: object
      properties:
        scorer_id:
          type: integer
          description: Unique scorer identifier
        name:
          type: string
          description: Name of the scorer
        minute:
          type: integer
          description: Minute where the
    Sponsor:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string

